# fly.toml app configuration file generated for public-repo on 2026-03-24T14:56:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'public-repo'
primary_region = 'lhr'

[build]

[env]
  PUBLIC_API_HOST = "0.0.0.0"
  PUBLIC_API_PORT = "8080"
  PUBLIC_API_DB_PATH = "/app/ave-database"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.health]
    type = "http"
    port = 8080
    path = "/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
